//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_M_Credit_Term> TB_M_Credit_Term { get; set; }
        public virtual DbSet<TB_M_Delivery_Type> TB_M_Delivery_Type { get; set; }
        public virtual DbSet<TB_M_STATUS> TB_M_STATUS { get; set; }
        public virtual DbSet<TB_R_BA> TB_R_BA { get; set; }
        public virtual DbSet<TB_R_CB_BA> TB_R_CB_BA { get; set; }
        public virtual DbSet<TB_R_CB_INVOICE> TB_R_CB_INVOICE { get; set; }
        public virtual DbSet<TB_R_CB_PACKAGE> TB_R_CB_PACKAGE { get; set; }
        public virtual DbSet<TB_R_INVOICE> TB_R_INVOICE { get; set; }
        public virtual DbSet<TB_R_PACKAGE> TB_R_PACKAGE { get; set; }
        public virtual DbSet<TB_S_BillingAppointmentReportData> TB_S_BillingAppointmentReportData { get; set; }
        public virtual DbSet<TB_S_BillingData> TB_S_BillingData { get; set; }
        public virtual DbSet<TB_S_CONFIG> TB_S_CONFIG { get; set; }
        public virtual DbSet<TB_S_InvoiceHeader> TB_S_InvoiceHeader { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounters { get; set; }
        public virtual DbSet<Hash> Hashes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobParameter> JobParameters { get; set; }
        public virtual DbSet<JobQueue> JobQueues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<vBillingAppointment> vBillingAppointments { get; set; }
        public virtual DbSet<vCB_BillingAppointment> vCB_BillingAppointment { get; set; }
        public virtual DbSet<vCB_PackageList> vCB_PackageList { get; set; }
        public virtual DbSet<vPackage> vPackages { get; set; }
        public virtual DbSet<vPackageList> vPackageLists { get; set; }
        public virtual DbSet<TB_M_HOLIDAYS> TB_M_HOLIDAYS { get; set; }
        public virtual DbSet<TB_M_Lab_Branch> TB_M_Lab_Branch { get; set; }
    
        public virtual ObjectResult<string> usp_AdhocGenerateBANumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_AdhocGenerateBANumber");
        }
    
        public virtual ObjectResult<usp_AdhocListInvoiceByInvoiceAddress_Result> usp_AdhocListInvoiceByInvoiceAddress(string iNVOICE_ID)
        {
            var iNVOICE_IDParameter = iNVOICE_ID != null ?
                new ObjectParameter("INVOICE_ID", iNVOICE_ID) :
                new ObjectParameter("INVOICE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AdhocListInvoiceByInvoiceAddress_Result>("usp_AdhocListInvoiceByInvoiceAddress", iNVOICE_IDParameter);
        }
    
        public virtual ObjectResult<usp_CriteriaSearch_CB_Result> usp_CriteriaSearch_CB(string bILL_TO_COMPANY, Nullable<System.DateTime> oVERRIDE_DATE_FROM, Nullable<System.DateTime> oVERRIDE_DATE_TO)
        {
            var bILL_TO_COMPANYParameter = bILL_TO_COMPANY != null ?
                new ObjectParameter("BILL_TO_COMPANY", bILL_TO_COMPANY) :
                new ObjectParameter("BILL_TO_COMPANY", typeof(string));
    
            var oVERRIDE_DATE_FROMParameter = oVERRIDE_DATE_FROM.HasValue ?
                new ObjectParameter("OVERRIDE_DATE_FROM", oVERRIDE_DATE_FROM) :
                new ObjectParameter("OVERRIDE_DATE_FROM", typeof(System.DateTime));
    
            var oVERRIDE_DATE_TOParameter = oVERRIDE_DATE_TO.HasValue ?
                new ObjectParameter("OVERRIDE_DATE_TO", oVERRIDE_DATE_TO) :
                new ObjectParameter("OVERRIDE_DATE_TO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CriteriaSearch_CB_Result>("usp_CriteriaSearch_CB", bILL_TO_COMPANYParameter, oVERRIDE_DATE_FROMParameter, oVERRIDE_DATE_TOParameter);
        }
    
        public virtual ObjectResult<usp_CriteriaSearchBillingAppointment_Result> usp_CriteriaSearchBillingAppointment(string cRITERIA_TYPE, string bA_NO, string bILL_TO_COMPANY, string qUOTE_NO, string iNVOICE_NO, string dELIVERY_TYPE, string iNVOICE_DATE_FROM, string iNVOICE_DATE_TO, string pACKAGE_NO, string pACKAGE_STATUS, string pACKAGE_CREATE_DATE_FROM, string pACKAGE_CREATE_DATE_TO, string pACKAGE_DELIVERY_DATE_FROM, string pACKAGE_DELIVERY_DATE_TO)
        {
            var cRITERIA_TYPEParameter = cRITERIA_TYPE != null ?
                new ObjectParameter("CRITERIA_TYPE", cRITERIA_TYPE) :
                new ObjectParameter("CRITERIA_TYPE", typeof(string));
    
            var bA_NOParameter = bA_NO != null ?
                new ObjectParameter("BA_NO", bA_NO) :
                new ObjectParameter("BA_NO", typeof(string));
    
            var bILL_TO_COMPANYParameter = bILL_TO_COMPANY != null ?
                new ObjectParameter("BILL_TO_COMPANY", bILL_TO_COMPANY) :
                new ObjectParameter("BILL_TO_COMPANY", typeof(string));
    
            var qUOTE_NOParameter = qUOTE_NO != null ?
                new ObjectParameter("QUOTE_NO", qUOTE_NO) :
                new ObjectParameter("QUOTE_NO", typeof(string));
    
            var iNVOICE_NOParameter = iNVOICE_NO != null ?
                new ObjectParameter("INVOICE_NO", iNVOICE_NO) :
                new ObjectParameter("INVOICE_NO", typeof(string));
    
            var dELIVERY_TYPEParameter = dELIVERY_TYPE != null ?
                new ObjectParameter("DELIVERY_TYPE", dELIVERY_TYPE) :
                new ObjectParameter("DELIVERY_TYPE", typeof(string));
    
            var iNVOICE_DATE_FROMParameter = iNVOICE_DATE_FROM != null ?
                new ObjectParameter("INVOICE_DATE_FROM", iNVOICE_DATE_FROM) :
                new ObjectParameter("INVOICE_DATE_FROM", typeof(string));
    
            var iNVOICE_DATE_TOParameter = iNVOICE_DATE_TO != null ?
                new ObjectParameter("INVOICE_DATE_TO", iNVOICE_DATE_TO) :
                new ObjectParameter("INVOICE_DATE_TO", typeof(string));
    
            var pACKAGE_NOParameter = pACKAGE_NO != null ?
                new ObjectParameter("PACKAGE_NO", pACKAGE_NO) :
                new ObjectParameter("PACKAGE_NO", typeof(string));
    
            var pACKAGE_STATUSParameter = pACKAGE_STATUS != null ?
                new ObjectParameter("PACKAGE_STATUS", pACKAGE_STATUS) :
                new ObjectParameter("PACKAGE_STATUS", typeof(string));
    
            var pACKAGE_CREATE_DATE_FROMParameter = pACKAGE_CREATE_DATE_FROM != null ?
                new ObjectParameter("PACKAGE_CREATE_DATE_FROM", pACKAGE_CREATE_DATE_FROM) :
                new ObjectParameter("PACKAGE_CREATE_DATE_FROM", typeof(string));
    
            var pACKAGE_CREATE_DATE_TOParameter = pACKAGE_CREATE_DATE_TO != null ?
                new ObjectParameter("PACKAGE_CREATE_DATE_TO", pACKAGE_CREATE_DATE_TO) :
                new ObjectParameter("PACKAGE_CREATE_DATE_TO", typeof(string));
    
            var pACKAGE_DELIVERY_DATE_FROMParameter = pACKAGE_DELIVERY_DATE_FROM != null ?
                new ObjectParameter("PACKAGE_DELIVERY_DATE_FROM", pACKAGE_DELIVERY_DATE_FROM) :
                new ObjectParameter("PACKAGE_DELIVERY_DATE_FROM", typeof(string));
    
            var pACKAGE_DELIVERY_DATE_TOParameter = pACKAGE_DELIVERY_DATE_TO != null ?
                new ObjectParameter("PACKAGE_DELIVERY_DATE_TO", pACKAGE_DELIVERY_DATE_TO) :
                new ObjectParameter("PACKAGE_DELIVERY_DATE_TO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CriteriaSearchBillingAppointment_Result>("usp_CriteriaSearchBillingAppointment", cRITERIA_TYPEParameter, bA_NOParameter, bILL_TO_COMPANYParameter, qUOTE_NOParameter, iNVOICE_NOParameter, dELIVERY_TYPEParameter, iNVOICE_DATE_FROMParameter, iNVOICE_DATE_TOParameter, pACKAGE_NOParameter, pACKAGE_STATUSParameter, pACKAGE_CREATE_DATE_FROMParameter, pACKAGE_CREATE_DATE_TOParameter, pACKAGE_DELIVERY_DATE_FROMParameter, pACKAGE_DELIVERY_DATE_TOParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> usp_GenerateGUID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("usp_GenerateGUID");
        }
    
        public virtual ObjectResult<string> usp_GetNewRunningNo(string isBilling, string packageDeliveryType, string packagelabBranch)
        {
            var isBillingParameter = isBilling != null ?
                new ObjectParameter("IsBilling", isBilling) :
                new ObjectParameter("IsBilling", typeof(string));
    
            var packageDeliveryTypeParameter = packageDeliveryType != null ?
                new ObjectParameter("PackageDeliveryType", packageDeliveryType) :
                new ObjectParameter("PackageDeliveryType", typeof(string));
    
            var packagelabBranchParameter = packagelabBranch != null ?
                new ObjectParameter("PackagelabBranch", packagelabBranch) :
                new ObjectParameter("PackagelabBranch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetNewRunningNo", isBillingParameter, packageDeliveryTypeParameter, packagelabBranchParameter);
        }
    
        public virtual ObjectResult<string> usp_GetNewRunningNo_CB(string isBilling, string packageDeliveryType, string packagelabBranch)
        {
            var isBillingParameter = isBilling != null ?
                new ObjectParameter("IsBilling", isBilling) :
                new ObjectParameter("IsBilling", typeof(string));
    
            var packageDeliveryTypeParameter = packageDeliveryType != null ?
                new ObjectParameter("PackageDeliveryType", packageDeliveryType) :
                new ObjectParameter("PackageDeliveryType", typeof(string));
    
            var packagelabBranchParameter = packagelabBranch != null ?
                new ObjectParameter("PackagelabBranch", packagelabBranch) :
                new ObjectParameter("PackagelabBranch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetNewRunningNo_CB", isBillingParameter, packageDeliveryTypeParameter, packagelabBranchParameter);
        }
    
        public virtual ObjectResult<usp_top1_invoice_Result> usp_top1_invoice(string bILL_TO_COMPANY)
        {
            var bILL_TO_COMPANYParameter = bILL_TO_COMPANY != null ?
                new ObjectParameter("BILL_TO_COMPANY", bILL_TO_COMPANY) :
                new ObjectParameter("BILL_TO_COMPANY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_top1_invoice_Result>("usp_top1_invoice", bILL_TO_COMPANYParameter);
        }
    }
}
