//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_STATUS
    {
        public System.Guid STATUS_ID { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_NAME { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCTYPE_SUB { get; set; }
    }
}
