//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_Delivery_Type
    {
        public System.Guid Delivery_Type_ID { get; set; }
        public string Delivery_Code { get; set; }
        public string Delivery_Type { get; set; }
    }
}
