//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_HOLIDAYS
    {
        public int HOLIDAYS_ID { get; set; }
        public Nullable<System.DateTime> HOLIDAYS_DATE { get; set; }
        public string HOLIDAYS_DAYS { get; set; }
        public string COMMENT { get; set; }
    }
}
