//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_Credit_Term
    {
        public System.Guid Credit_Term_ID { get; set; }
        public string Credit_Code { get; set; }
        public string Credit_Term_Value { get; set; }
    }
}
