//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_BA
    {
        public System.Guid BA_ID { get; set; }
        public Nullable<System.Guid> Package_ID { get; set; }
        public string BA_No { get; set; }
        public string Quote_No { get; set; }
        public string Invoice_To_Comany { get; set; }
        public string Invoice_To_Person { get; set; }
        public string Invoice_To_Address { get; set; }
        public string Invoice_Cust_Code { get; set; }
        public string Invoice_Note { get; set; }
        public string Report_To_Comany { get; set; }
        public string Reports_To_Address { get; set; }
        public string Reports_To_Tel { get; set; }
        public string Invoice_To_Tel { get; set; }
        public string Delivery_Type { get; set; }
        public string Delivery_Lab { get; set; }
        public string Status_Code { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
