//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_CB_BA
    {
        public System.Guid CB_ID { get; set; }
        public Nullable<System.Guid> CB_Package_ID { get; set; }
        public string CB_No { get; set; }
        public string CB_Quote_No { get; set; }
        public string CB_Invoice_To_Comany { get; set; }
        public string CB_Invoice_To_Person { get; set; }
        public string CB_Invoice_To_Address { get; set; }
        public string CB_Invoice_Cust_Code { get; set; }
        public string CB_Invoice_Note { get; set; }
        public string CB_Report_To_Comany { get; set; }
        public string CB_Reports_To_Address { get; set; }
        public string CB_Reports_To_Tel { get; set; }
        public string CB_Invoice_To_Tel { get; set; }
        public string CB_Delivery_Type { get; set; }
        public string CB_Delivery_Lab { get; set; }
        public string CB_Status_Code { get; set; }
        public Nullable<System.DateTime> CB_CreateDate { get; set; }
        public string CB_CreateBy { get; set; }
        public Nullable<System.DateTime> CB_UpdateDate { get; set; }
        public string CB_UpdateBy { get; set; }
    }
}
