//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_CB_INVOICE
    {
        public System.Guid CB_Invoice_ID { get; set; }
        public Nullable<System.Guid> CB_ID { get; set; }
        public string CB_Invoice_No { get; set; }
        public string CB_Cust_Code { get; set; }
        public string CB_Bill_To_Company { get; set; }
        public string CB_Delivery_Address { get; set; }
        public string CB_Delivery_To_Person { get; set; }
        public string CB_Delivery_To_Tel { get; set; }
        public string CB_Report_To_Comany { get; set; }
        public string CB_Reports_To_Address { get; set; }
        public string CB_Reports_To_Tel { get; set; }
        public Nullable<System.DateTime> CB_Invoice_Issue_Date { get; set; }
        public Nullable<System.DateTime> CB_Invoice_Date_Override { get; set; }
        public Nullable<decimal> CB_Total_Invoice_Amount_Inc_Vat { get; set; }
        public string CreditTerm { get; set; }
        public string Status_Code { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
