//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_CB_PACKAGE
    {
        public System.Guid CB_Package_ID { get; set; }
        public string CB_Package_No { get; set; }
        public string CB_Package_Name { get; set; }
        public Nullable<System.DateTime> CB_Package_Delivery_Date { get; set; }
        public string CB_Package_DESC { get; set; }
        public string CB_Invoice_To_Address { get; set; }
        public string CB_Invoice_To_Person { get; set; }
        public string CB_Invoice_To_Cust_Code { get; set; }
        public string CB_Invoice_To_Company { get; set; }
        public string CB_Invoice_Delivery_Phone { get; set; }
        public string CB_Invoice_Delivery_Type { get; set; }
        public string CB_Invoice_Delivery_Lab { get; set; }
        public Nullable<System.DateTime> CB_Logistics_Delivery_Date { get; set; }
        public string CB_Status_Code { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
