//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_S_BillingData
    {
        public System.Guid ID { get; set; }
        public string InvoiceNumber { get; set; }
        public string Workorder { get; set; }
        public string Site { get; set; }
        public string NAVAccountNumber { get; set; }
        public string Project { get; set; }
        public string PurchaseOrder { get; set; }
        public string ReportToContact { get; set; }
        public string ReportToOffice { get; set; }
        public string ReportToClient { get; set; }
        public string InvoiceContact { get; set; }
        public string Laboratory { get; set; }
        public string ClientManager { get; set; }
        public string ActivityCode { get; set; }
        public string AFENumber { get; set; }
        public string ApproverCode { get; set; }
        public string ContractNumber { get; set; }
        public string CostCenterClient { get; set; }
        public string GLAccount { get; set; }
        public string LegalSiteDescriptionLSD { get; set; }
        public string ProjectManagerClientSide { get; set; }
        public string InvoiceFile { get; set; }
        public string CoCFile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
