//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_S_CONFIG
    {
        public System.Guid Config_ID { get; set; }
        public string Config_Name { get; set; }
        public string Config_Value { get; set; }
    }
}
