//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_S_BillingAppointmentReportData
    {
        public System.Guid ID { get; set; }
        public string InvoiceId { get; set; }
        public string InvoiceDeliveryType { get; set; }
        public string AnalysisReportDeliveryType { get; set; }
        public string InvoiceDeliveryLaboratory { get; set; }
        public string AnalysisReportDeliveryLaboratory { get; set; }
        public string QuoteCode { get; set; }
        public string CreditTerm { get; set; }
        public string InvoiceDeliveryClientCode { get; set; }
        public string AnalysisReportDeliverToClientCode { get; set; }
        public string AnalysisReportDeliverToClientName { get; set; }
        public string InvoiceDeliveryClientName { get; set; }
        public string InvoiceDeliverToPersonName { get; set; }
        public string InvoiceDeliverToPersonTelephone { get; set; }
        public string InvoiceDeliverToPersonMobile { get; set; }
        public string AnalysisReportDeliverToPersonName { get; set; }
        public string AnalysisReportDeliverToPersonTelephone { get; set; }
        public string AnalysisReportDeliverToPersonMobile { get; set; }
        public string InvoiceDeliverToOffice { get; set; }
        public string InvoiceDeliverToAddress1 { get; set; }
        public string InvoiceDeliverToAddress2 { get; set; }
        public string InvoiceDeliverToAddress3 { get; set; }
        public string InvoiceDeliverToCity { get; set; }
        public string InvoiceDeliverToState { get; set; }
        public string InvoiceDeliverToZip { get; set; }
        public string InvoiceDeliverToLocation { get; set; }
        public string AnalysisReportDeliverToOffice { get; set; }
        public string AnalysisReportDeliverToAddress1 { get; set; }
        public string AnalysisReportDeliverToAddress2 { get; set; }
        public string AnalysisReportDeliverToAddress3 { get; set; }
        public string AnalysisReportDeliverToCity { get; set; }
        public string AnalysisReportDeliverToState { get; set; }
        public string AnalysisReportDeliverToZip { get; set; }
        public string AnalysisReportDeliverToLocation { get; set; }
        public string InvoiceDeliveryNotes { get; set; }
        public string InvoiceDeliveryProcess { get; set; }
        public Nullable<System.DateTime> InvoiceIssuedDate { get; set; }
        public Nullable<System.DateTime> InvoiceDateOverride { get; set; }
        public string InvoiceNumbersIncludedInSearch { get; set; }
        public string TotalInvoiceAmountIncludingVat { get; set; }
        public string ReportToPersonName { get; set; }
        public string ReportToAddress1 { get; set; }
        public string ReportToAddress2 { get; set; }
        public string ReportToAddress3 { get; set; }
        public string ReportToCity { get; set; }
        public string ReportToState { get; set; }
        public string ReportToZip { get; set; }
        public string ReportToLocation { get; set; }
        public string BillToClientCode { get; set; }
        public string BillToClientName { get; set; }
        public string BillToContactPerson { get; set; }
        public string PaymentDeliveryProcess { get; set; }
        public string PaymentDeliveryNotes { get; set; }
        public string ReportLocation { get; set; }
        public string GenerateBillingAppointmentPerInvoice { get; set; }
        public string InvoicePaid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CeateBy { get; set; }
        public string ConsolidateBillingFlag { get; set; }
        public string ConsolidateBillingDeliverToOffice { get; set; }
        public string ConsolidateBillingToPersonName { get; set; }
        public string ConsolidateBillingDeliverToAddress1 { get; set; }
        public string ConsolidateBillingDeliverToAddress2 { get; set; }
        public string ConsolidateBillingDeliverToAddress3 { get; set; }
        public string ConsolidateBillingDeliverToCity { get; set; }
        public string ConsolidateBillingDeliverToState { get; set; }
        public string ConsolidateBillingDeliverToZip { get; set; }
        public string ConsolidateBillingDeliverToLocation { get; set; }
        public string ConsolidateBillingClientCode { get; set; }
        public string ConsolidateBillingCompanyName { get; set; }
        public string ConsolidateBillingToTelephone { get; set; }
        public string ConsolidateBillingToMobile { get; set; }
        public string ConsolidateBillingOtherLocation { get; set; }
    }
}
