//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCB_BillingAppointment
    {
        public Nullable<System.Guid> CB_Package_ID { get; set; }
        public System.Guid CB_ID { get; set; }
        public string CB_No { get; set; }
        public Nullable<System.Guid> CB_Invoice_ID { get; set; }
        public string CB_Invoice_No { get; set; }
        public string CB_Invoice_Cust_Code { get; set; }
        public string CB_Quote_No { get; set; }
        public string CB_Bill_To_Company { get; set; }
        public string CB_Invoice_To_Address { get; set; }
        public string CB_Reports_To_Address { get; set; }
        public string DiffAddress { get; set; }
        public string CB_Invoice_Note { get; set; }
        public string CB_Delivery_Type { get; set; }
        public string Delivery_Name { get; set; }
        public string CB_Status_Code { get; set; }
        public string STATUS_NAME { get; set; }
        public string CB_CreateBy { get; set; }
        public Nullable<System.DateTime> CB_CreateDate { get; set; }
        public string CB_UpdateBy { get; set; }
        public Nullable<System.DateTime> CB_UpdateDate { get; set; }
    }
}
