//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPackageList
    {
        public System.Guid Package_ID { get; set; }
        public string Package_No { get; set; }
        public string Package_Name { get; set; }
        public Nullable<System.DateTime> Package_Delivery_Date { get; set; }
        public Nullable<System.DateTime> Logistics_Delivery_Date { get; set; }
        public string Status_Code { get; set; }
        public string STATUS_NAME { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
