//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPackage
    {
        public Nullable<System.Guid> Package_ID { get; set; }
        public Nullable<System.Guid> BA_ID { get; set; }
        public System.Guid Invoice_ID { get; set; }
        public string Package_No { get; set; }
        public string Package_Name { get; set; }
        public string BA_No { get; set; }
        public string Invoice_No { get; set; }
        public string Quote_No { get; set; }
        public string Cust_Code { get; set; }
        public string Bill_To_Company { get; set; }
        public string Delivery_To_Person { get; set; }
        public string Delivery_To_Tel { get; set; }
        public string Delivery_Address { get; set; }
        public string Report_To_Comany { get; set; }
        public string Reports_To_Tel { get; set; }
        public string Reports_To_Address { get; set; }
        public string Invoice_Note { get; set; }
        public string DiffAddress { get; set; }
        public Nullable<System.DateTime> Invoice_Issue_Date { get; set; }
        public Nullable<System.DateTime> Invoice_Date_Override { get; set; }
        public Nullable<decimal> Total_Invoice_Amount_Inc_Vat { get; set; }
        public string CreditTerm { get; set; }
        public string Delivery_Type { get; set; }
        public string Status_Name { get; set; }
        public Nullable<System.DateTime> Package_Delivery_Date { get; set; }
        public Nullable<System.DateTime> Logistics_Delivery_Date { get; set; }
        public string Status_Code { get; set; }
        public string Expr1 { get; set; }
        public string pack_CreateBy { get; set; }
        public Nullable<System.DateTime> pack_CreateDate { get; set; }
        public string BA_CreateBy { get; set; }
        public Nullable<System.DateTime> BA_CreateDate { get; set; }
        public string inv_CreateBy { get; set; }
        public Nullable<System.DateTime> inv_CreateDate { get; set; }
    }
}
